language: go

go:
  - 1.5
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
after_success:
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - go get github.com/tcnksm/ghr
  - make xcompile
  - ghr -t $GITHUB_TOKEN -u allegro --replace `shell awk -F\" '/^const Version/ { print $$2 }' main.go` dist/

script: make test
